### PR TITLE
v1.2.0

### PR DESCRIPTION
**Pull request by jaredhendrickson13**
- Adds /api/v1/system/halt endpoint to shutdown pfSense
- Adds /api/v1/system/reboot endpoint to reboot pfSense
- Adds /api/v1/firewall/traffic_shaper endpoint to interact with interface traffic shapers
- Adds /api/v1/firewall/traffic_shaper/queue endpoint to interact with interface traffic shaper queues
- Adds /api/v1/firewall/traffic_shaper/limiter endpoint to interact with limiters
- Adds /api/v1/firewall/traffic_shaper/limiter/bandwidth endpoint to interact with limiter bandwidth settings
- Adds /api/v1/firewall/traffic_shaper/limiter/queue endpoint to interact with limiter queues
- Adds /api/v1/firewall/schedule endpoint to interact with firewall schedules
- Adds /api/v1/firewall/schedule/time_range endpoint to interact with schedule time ranges
- Adds ability to specify firewalls schedule and shapers in firewall rules on /api/v1/firewall/rule endpoint
- Adds support for PUT requests on /api/v1/system/api to update the API configuration
- Adds endpoint for /api/v1/services/ntpd to read and update the NTP configuration
- Adds endpoint for /api/v1/services/ntpd/time_server to add or remove NTP timeservers
- Adds documentation for NTP endpoints
- Adds unit tests for NTP endpoints
- Optimizes /api/v1/firewall/states/size endpoint 
- Overhauls the API settings page with a  simpler, more organized design.
- Adds the `custom_headers` and `allow_options` API configuration
- Updates the /api/v1/system/api endpoint to include new API configuration values
- Updates APIEndpoint.inc to add custom response headers and OPTIONS requests when configured
- Updates documentation to include the new configuration options

### CODE REVIEW

**Comment by jaredhendrickson13** [comment]
Test builds are available:

pfSense 2.4:
`pkg add https://github.com/jaredhendrickson13/pfsense-api/files/6039720/pfSense-2.4-pkg-API-1.2_0beta.zip && /etc/rc.restart_webgui`
pfSense 2.5:
`pkg add https://github.com/jaredhendrickson13/pfsense-api/files/6039721/pfSense-2.5-pkg-API-1.2_0beta.zip && /etc/rc.restart_webgui`
pfSense 2.6:
`pkg add https://github.com/jaredhendrickson13/pfsense-api/files/6039722/pfSense-2.6-pkg-API-1.2_0beta.zip && /etc/rc.restart_webgui`

[pfSense-2.4-pkg-API-1.2_0beta.zip](https://github.com/jaredhendrickson13/pfsense-api/files/6039720/pfSense-2.4-pkg-API-1.2_0beta.zip)
[pfSense-2.5-pkg-API-1.2_0beta.zip](https://github.com/jaredhendrickson13/pfsense-api/files/6039721/pfSense-2.5-pkg-API-1.2_0beta.zip)
[pfSense-2.6-pkg-API-1.2_0beta.zip](https://github.com/jaredhendrickson13/pfsense-api/files/6039722/pfSense-2.6-pkg-API-1.2_0beta.zip)

**Comment by mwoolweaver** [comment]
after installing the package provided for 2.6 i got the following crash

```
Crash report begins.  Anonymous machine information:

amd64
12.2-STABLE
FreeBSD 12.2-STABLE 9758000a7ba(devel-12) pfSense

Crash report details:

PHP Errors:
[26-Feb-2021 23:38:02 US/Central] PHP Warning:  file_get_contents(/usr/local/share/pfSense-pkg-API/backup.json): failed to open stream: No such file or directory in /usr/local/share/pfSense-pkg-API/manage.php on line 61



No FreeBSD crash data found.
			
```

doesn't seem to be anything major just a missing backup. possibly cause i never made one.

**Comment by jaredhendrickson13** [comment]
@mwoolweaver that is somewhat expected. The development builds of pfSense will report both PHP warnings _and_ errors where as the mainline releases only report PHP errors. It shouldn't cause any problems, but still a good idea to fix.

**Comment by mwoolweaver** [comment]
the only the other thing I've noticed is the doc pages seem a bit off 

This is what I see when using

Brave:

chromium_docs

Firefox:

firefox_docs

Chromium:

brave_docs

**Comment by jaredhendrickson13** [comment]
@mwoolweaver good eye, that is an issue I've had on my radar for some time. Both the UI and README.md documentation are generated using an awesome tool called docgen that creates the documentation from a Postman collection file. About a month or so ago it stopped generating items within subfolders in the Postman collection. Not sure if this was a change on Postman's end or docgen's, but there is an open issue (thedevsaddam/docgen#46) I've been following on the docgen repo. My plan is to hold off for now until v1.2.0 is closer to release and if there is no official fix then, I'll simply remove those items from the subfolders until there's a more permanent fix.

**Comment by degas2226** [comment]
@jaredhendrickson13 Shall we have one beta release here to verify the functionalities.

**Comment by jaredhendrickson13** [comment]
@degas2226 yes, test builds are available in my previous [comment](https://github.com/jaredhendrickson13/pfsense-api/pull/71#issuecomment-785489193) above

**Comment by jaredhendrickson13** [comment]
Completed beta builds are ready. Would greatly appreciate anyone willing to test:

pfSense 2.4:
`pkg add https://github.com/jaredhendrickson13/pfsense-api/files/6166552/pfSense-2.4-pkg-API-1.2_0beta.zip && /etc/rc.restart_webgui`
pfSense 2.5:
`pkg add https://github.com/jaredhendrickson13/pfsense-api/files/6166553/pfSense-2.5-pkg-API-1.2_0beta.zip && /etc/rc.restart_webgui`
pfSense 2.6:
`pkg add https://github.com/jaredhendrickson13/pfsense-api/files/6166554/pfSense-2.6-pkg-API-1.2_0beta.zip && /etc/rc.restart_webgui`

[pfSense-2.4-pkg-API-1.2_0.zip](https://github.com/jaredhendrickson13/pfsense-api/files/6166552/pfSense-2.4-pkg-API-1.2_0.zip)
[pfSense-2.5-pkg-API-1.2_0.zip](https://github.com/jaredhendrickson13/pfsense-api/files/6166553/pfSense-2.5-pkg-API-1.2_0.zip)
[pfSense-2.6-pkg-API-1.2_0.zip](https://github.com/jaredhendrickson13/pfsense-api/files/6166554/pfSense-2.6-pkg-API-1.2_0.zip)

**Pull request merged**
