### PR TITLE
Implemented handling of CA certificates

### PR DESCRIPTION
**Pull request by mj84**
Hi there,

I needed to manage CA certificates on a pfSense using an API, so I extended yours :)

### CODE REVIEW

**Comment by jaredhendrickson13** [comment]
Hey! 

Thanks for your patience. This PR looks great, I appreciate the work put into this. Give me a few days to review and test before merging. 

Thanks again!

**Review by jaredhendrickson13 — CHANGES_REQUESTED** [review]
Thanks again for your patience! This all looks great to me. Would you mind updating the PR to merge this feature into my `v130` branch? That will help me include these features into the beta builds and automated testing for that release.

Thank you!

**Comment by mj84** [comment]
Hi there, great to hear that :)
I just changed the PR to be merged in your `v130` branch, was this what you meant?
Greetings

**Review by jaredhendrickson13 — APPROVED** [review]
Yes that's perfect. Thank you!

**Pull request merged**
