### PR TITLE
v1.3.0

### PR DESCRIPTION
**Pull request by jaredhendrickson13**
- Adds /api/v1/services/dnsmasq endpoint to read the dnsmasq configuration 
- Adds /api/v1/services/dnsmasq/host_override endpoint to create, read, update and delete dnsmasq host overrides (#109)
- Adds /api/v1/services/dnsmasq/host_override/alias endpoint to create dnsmasq host override alias entries 
- Adds /api/v1/services/dnsmasq/start endpoint to start the dnsmasq service
- Adds /api/v1/services/dnsmasq/stop endpoint to stop the dnsmasq service 
- Adds /api/v1/services/dnsmasq/restart endpoint to restart the dnsmasq service
- Adds HA sync feature to API settings (#97)
- Adds /api/v1/system/ca endpoint to manage system CA certificates (#125)
- Adds /api/v1/system/api/version endpoint to pull API version information (#151)
- Adds Update tab to API UI page for easy updates (#151)
- Adds /api/v1/diagnostics/command_prompt endpoint to remotely execute shell commands (#144)
- Adds /api/v1/status/openvpn endpoint to check OpenVPN server and client statuses (#61)
- Adds /api/v1/system/console endpoint to configure console related settings
- Adds /api/v1/interface/bridge endpoint to configure bridged interfaces
- Adds /api/v1/services/unbound/access_list and /api/v1/services/unbound/access_list/row endpoints to configure Unbound access lists
- Fixes bug that prevent zero value system tunables from being set
- Fixes bug that prevent DHCP Server from being updated when pfSense was setup with a WAN interface only
- Moves existing /api/v1/routing/gateway to /api/v1/routing/gateway/detail to make the functionality easier to understand and use (#110)
- Updates /api/v1/routing/gateway to only return gateway objects stored in configuration (#110)
- Removes all references and conditions for pfSense 2.4
- Adds /api/v1/firewall/rule/flush endpoint to delete all firewall rules
- Updates /api/v1/system/ca to allow creation of internal and intermediate CAs (#34)
- Updates /api/v1/system/certificate to allow creation of internal server and user certificates (#34)
- Updates /api/v1/user to allow assignment of user certificates to users (#34)
- Adds /api/v1/services/openvpn/csc endpoint to configure OpenVPN client specific overrides (#154) 
- Fixes bug that allowed non-numeric rule tracker IDs to be validated during DELETE requests to /api/v1/firewall/rule
- Updates /api/v1/system/config to allow PUT requests that update the entire pfSense configuration
- Adds /api/v1/system/notifications/email to update and read the SMTP notification settings

### CODE REVIEW

**Comment by jaredhendrickson13** [comment]
Beta builds are available. I'll try to keep these updated:

pfSense 2.5
```
pkg add https://github.com/jaredhendrickson13/pfsense-api/files/6216326/pfSense-2.5-pkg-API-1.3_0beta.zip && /etc/rc.restart_webgui
```
pfSense 2.6
```
pkg add https://github.com/jaredhendrickson13/pfsense-api/files/6216327/pfSense-2.5-pkg-API-1.3_0beta.zip && /etc/rc.restart_webgui
```

[pfSense-2.5-pkg-API-1.3_0beta.zip](https://github.com/jaredhendrickson13/pfsense-api/files/6216326/pfSense-2.5-pkg-API-1.3_0beta.zip)
[pfSense-2.6-pkg-API-1.3_0beta.zip](https://github.com/jaredhendrickson13/pfsense-api/files/6216327/pfSense-2.6-pkg-API-1.3_0beta.zip)

**Comment by jaredhendrickson13** [comment]
Updated beta builds are available:

pfSense 2.5:
```pkg add https://github.com/jaredhendrickson13/pfsense-api/files/6460790/pfSense-2.5-pkg-API-v1.3_0beta.zip && /etc/rc.restart_webgui```

pfSense 2.6:
```pkg add https://github.com/jaredhendrickson13/pfsense-api/files/6460791/pfSense-2.6-pkg-API-v1.3_0beta.zip && /etc/rc.restart_webgui```

[pfSense-2.6-pkg-API-v1.3_0beta.zip](https://github.com/jaredhendrickson13/pfsense-api/files/6460791/pfSense-2.6-pkg-API-v1.3_0beta.zip)
[pfSense-2.5-pkg-API-v1.3_0beta.zip](https://github.com/jaredhendrickson13/pfsense-api/files/6460790/pfSense-2.5-pkg-API-v1.3_0beta.zip)

**Comment by degas2226** [comment]
Hi Jared,

I don't see beta package for 2.4 version of pfsense. Is this not supported for 2.4?

**Comment by jaredhendrickson13** [comment]
@degas2226 yes, with Netgate deprecating the 2.4 package repos it unfortunately becomes very difficult to maintain and perform automated testing for the package on 2.4 releases. Going forward (starting with v1.3.0) 2.5 will be the primary supported platform with 2.6 as a development preview. This also allows me to start implementing features that are specific to pfSense 2.5 and remove the extra code required to make the package backwards compatible with 2.4, which greatly increased the complexity for some of the code. 

That being said, it may still be possible to force the installation of the package on 2.4 using the `-f` flag after the `pkg add` command. I haven't tried this myself, but I would think most endpoints and functions would still operate. I would however expect things to start breaking as time goes on so doing so would be at your own risk.

**Pull request merged**
